version: "3.8"
services:
  # nginx:
  #   image: nginx:${TAG}-${NGINX}
  #   container_name: ${NGINX}
  #   build:
  #    context: ./container/${NGINX}
  #   networks:
  #     - front
  #   ports:
  #     - 443:443
  # wordpress:
  #   image: wordpress:${TAG}-${WORDPRESS}
  #   container_name: ${WORDPRESS}
  #   build:
  #    context: ./container/${WORDPRESS}
  #   networks:
  #     - front
  #     - back
  db:
    image: mariadb:${TAG}-${MARIADB}
    container_name: ${MARIADB}
    build:
      context: ./container/${MARIADB}
    environment:
      - MARIA_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    env_file:
      - .env
    # networks:
    #   - back
    volumes:
      - db-data:/home/${USER}/data

volumes:
  db-data:
    name: ${DATABASE_VOLUME}

# networks:
#   - front
#   - back
