services:
  nginx:
    image: nginx:${TAG}-nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        - WORDPRESS_DOMAIN_NAME=${WORDPRESS_DOMAIN_NAME}
    networks:
      - front
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    restart:
      always

  wordpress:
    image: wordpress:${TAG}-wordpress
    container_name: wordpress
    build:
     context: ./requirements/wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_CHARSET=${WORDPRESS_DB_CHARSET}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
    networks:
      - front
      - back
    volumes:
      - wp:/var/www/html
    restart:
      always

  mariadb:
    image: mariadb:${TAG}-mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      - MARIA_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIA_HOST_NAME=${MARIADB_HOST_NAME}
    networks:
      - back
    volumes:
      - db:/var/lib/mysql
    restart:
      always

volumes:
  wp:
    driver_opts:
      type: none
      o: bind
      device: /Users/sawamurashun/data/wordpress
      # device: /home/${USER}/data/wordpress

  db:
    driver_opts:
      type: none
      o: bind
      device: /Users/sawamurashun/data/mariadb
      # device: /home/${USER}/data/mariadb

networks:
    front:
        driver: bridge
    back:
        driver: bridge
