services:
  # nginx:
  #   image: nginx:${TAG}-${NGINX}
  #   container_name: ${NGINX}
  #   build:
  #    context: ./container/${NGINX}
  #   networks:
  #     - front
  #   ports:
  #     - 443:443
    # networks:
    #   - inception
    # volumes:
    #   - wp-volume:/home/${USER}/data/wordpress
    # restart:
    #   always
  # wordpress:
  #   image: wordpress:${TAG}-${WORDPRESS}
  #   container_name: ${WORDPRESS}
  #   build:
  #    context: ./container/${WORDPRESS}
  #   networks:
  #     - front
  #     - back
    # volumes:
    #   - wp-volume:/home/${USER}/data/wordpress
    # restart:
    #   always

  db:
    image: mariadb:${TAG}-mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      - MARIA_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    env_file:
      - .env
    networks:
      - back
    volumes:
      - db-volume:/var/lib/mysql
    restart:
      always

volumes:
  wp-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
    front:
        driver: bridge
    back:
        driver: bridge
# volumes:
#   db-data:
#     name: ${DATABASE_VOLUME}

# networks:
#   - front
#   - back
